// Lista negra inicial para filtrar prompts inapropiados en entorno educativo
// Incluye palabras y frases en español e inglés, variantes y errores comunes

export const BLACKLIST: string[] = [
  // Sexualidad y desnudez
  "sexo", "sexual", "desnudo", "desnuda", "desnudez", "nude", "naked", "boobs", "tetas", "pechos", "senos", "genitales", "pene", "vagina", "clítoris", "clitoris", "erección", "ereccion", "masturbar", "masturbación", "masturbacion", "porno", "pornografía", "pornografia", "porn", "erótico", "erotico", "erotic", "sensual", "s3nsual", "orgasmo", "orgasm", "orgía", "orgia", "orgy", "striptease", "fetiche", "fetish", "bdsm", "sadomasoquismo", "sadomasochism", "penetración", "penetracion", "penetrate", "penetrating", "cum", "semen", "esperma", "ejaculation", "eyaculación", "eyaculacion", "anal", "oral", "69", "cunnilingus", "felación", "felacion", "felatio", "sado", "bondage", "incesto", "incest", "zoofilia", "zoofilia", "bestialidad", "bestiality", "pedofilia", "pedofilia", "pedophile", "pedofilo", "pedófilo", "child porn", "child sexual", "child nude", "child naked", "child abuse", "abuso sexual", "abuso infantil", "abuso de menores",
  // Violencia
  "violencia", "violento", "violenta", "violence", "violent", "arma", "armas", "pistola", "revolver", "rifle", "escopeta", "arma blanca", "cuchillo", "navaja", "bala", "disparo", "disparar", "shoot", "gun", "guns", "knife", "knives", "blood", "sangre", "sangriento", "sangrienta", "sangriento", "sangrienta", "gore", "matar", "asesinar", "asesinato", "muerte", "morir", "suicidio", "suicide", "kill", "killing", "dead", "death", "tortura", "torture", "ahorcar", "ahorcamiento", "decapitar", "decapitación", "decapitation", "desmembrar", "desmembramiento", "dismember", "dismemberment", "autolesión", "autolesion", "self harm", "self-harm", "cutting", "cut", "bullying", "acoso", "acoso escolar", "bully", "bullying", "abusar", "abuso", "abusador",
  // Drogas y sustancias
  "droga", "drogas", "drug", "drugs", "cocaína", "cocaina", "cocaine", "marihuana", "marijuana", "weed", "porro", "joint", "heroína", "heroina", "heroin", "crack", "lsd", "ácido", "acido", "acid", "pastilla", "pastillas", "píldora", "pildora", "pills", "tabaco", "cigarro", "cigarrillo", "cigarette", "smoke", "smoking", "alcohol", "borracho", "borracha", "borrachos", "borrachera", "drunk", "vodka", "tequila", "cerveza", "beer", "whisky", "whiskey", "licor", "liquor",
  // Discriminación y odio
  "racista", "racismo", "racist", "hate", "odio", "homofobia", "homofóbico", "homofobico", "homophobic", "homophobia", "xenofobia", "xenofóbico", "xenofobico", "xenophobic", "xenophobia", "discriminar", "discriminación", "discriminacion", "discrimination", "bullying", "bully", "acoso", "acosar", "acosador", "acosadora", "insulto", "insultar", "insult", "insulting", "grosero", "grosera", "grosería", "groseria", "swear", "swearing", "curse", "cursing", "maldecir", "maldito", "maldita",
  // Otros temas no aptos
  "terror", "horror", "miedo extremo", "susto", "asustar", "asustado", "asustada", "scare", "scary", "horror", "terror", "creepy", "creepypasta", "demonio", "demonios", "demon", "demons", "diablo", "devil", "satan", "satán", "satanás", "fantasma", "fantasmas", "ghost", "ghosts", "espíritu", "espiritu", "espíritus", "espiritus", "spirit", "spirits", "posesión", "posesion", "possessed", "possess", "possessing", "ritual", "rituales", "rituals", "ritualistic", "ritualista", "ritualístico", "ritualistico"
];

// Expresiones regulares para detectar variantes y camuflajes
export const BLACKLIST_REGEX: RegExp[] = [
  /s[e3]xo/i,
  /s[e3]nsual/i,
  /d[e3]snud[oa]/i,
  /n[a4]k[e3]d/i,
  /b[o0]{2}bs/i,
  /t[e3]tas?/i,
  /p[e3]chos?/i,
  /s[e3]nos?/i,
  /g[e3]nital(es)?/i,
  /p[e3]n[e3]/i,
  /v[a4]gina/i,
  /cl[i1]t[o0]r[i1]s/i,
  /masturba/i,
  /p[o0]rn/i,
  /er[o0]tic[oa]?/i,
  /[o0]rg[i1][a4]/i,
  /cum/i,
  /s[e3]men/i,
  /[e3]sperma/i,
  /[e3]jacul/i,
  /anal/i,
  /[o0]ral/i,
  /cunnilingus/i,
  /fel[a4]c[i1][o0]n?/i,
  /s[a4]d[o0]/i,
  /bondage/i,
  /incest[oa]?/i,
  /zo[o0]fil[i1][a4]/i,
  /bestial/i,
  /ped[o0]fil[i1][a4o0e3]/i,
  /child\s*(porn|sexual|nude|naked|abuse)/i,
  /abuso\s*(sexual|infantil|de\s*menores)/i,
  /viol[e3]n(cia|to|ta)/i,
  /viol[e3]nce/i,
  /arma(s)?/i,
  /pistola/i,
  /gun(s)?/i,
  /knife(s)?/i,
  /blood/i,
  /sangr(e|iento|ienta)/i,
  /gore/i,
  /matar/i,
  /kill/i,
  /suicid[ioe]/i,
  /tortur[ae]/i,
  /ahorc[ae]/i,
  /decapit[a4][cç][i1][o0]n?/i,
  /dismember/i,
  /autoles[i1][o0]n/i,
  /self[-_\s]?harm/i,
  /cut(ting)?/i,
  /bully(ing)?/i,
  /acoso/i,
  /abus[ao]r?/i,
  /dr[o0]g[aeas]/i,
  /cocain[a4e3]/i,
  /marihuan[a4]/i,
  /marijuana/i,
  /weed/i,
  /joint/i,
  /hero[i1]n[a4]?/i,
  /crack/i,
  /lsd/i,
  /acid[o0]?/i,
  /pastill[aeas]/i,
  /p[i1]ldor[aeas]/i,
  /pills?/i,
  /tabaco/i,
  /cigar(r[io])?/i,
  /cigarette/i,
  /smok(e|ing)/i,
  /alcohol/i,
  /drunk/i,
  /vodka/i,
  /tequila/i,
  /cerveza/i,
  /beer/i,
  /whisk[ey]/i,
  /licor/i,
  /liquor/i,
  /racis[mt][ao]?/i,
  /hate/i,
  /homof[o0]b[i1][co]/i,
  /xenof[o0]b[i1][co]/i,
  /discrimin[a4][cç][i1][o0]n?/i,
  /insult[oa]?/i,
  /groser[i1][a4]/i,
  /swear/i,
  /curse/i,
  /maldecir/i,
  /terror/i,
  /horror/i,
  /scare/i,
  /creepy/i,
  /demon[i1][oa]s?/i,
  /diabl[oa]/i,
  /devil/i,
  /satan[a4]?/i,
  /fantasm[ao]s?/i,
  /ghosts?/i,
  /esp[i1]rit[uo]s?/i,
  /possess/i,
  /ritual/i
];